create table DEPARTMENT
(
	ID NUMERIC(5) not null primary key,
	NAME VARCHAR(20) not null,
	MANAGER_ID NUMERIC(5) default 0 not null
);

create table EMPLOYEE
(
	ID NUMERIC(5) not null primary key,
	FIRST_NAME VARCHAR(20) not null,
	LAST_NAME VARCHAR(20) not null,
	ADRESS VARCHAR(20),
	HIRING_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	DEPT_ID NUMERIC(5) not null,
	SEX VARCHAR(5) default 'F' not null,
	PHONE VARCHAR(20),
	POSITION_ID NUMERIC(5) not null
);

ALTER TABLE EMPLOYEE
ADD FOREIGN KEY (DEPT_ID)
REFERENCES EMPLOYEE(ID);

ALTER TABLE DEPARTMENT
ADD FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEE(ID);


INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (1, '2012-03-25', NULL, 5, 'Carlos', 'Once', '13406877', 'M', 1);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (2, '2014-07-25', NULL, 3, 'Bridget', 'Carlson', '13456877', 'F', 2);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (3, '2013-07-17', NULL, 1, 'Allison', 'Marks', '135676877', 'F', 1);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (4, '2014-08-06', NULL, 3, 'James', 'Buchanon', '13456878', 'M', 2);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (5, '2014-08-07', NULL, 5, 'Mark', 'Forever', '23145688', 'M', 1);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (6, '2014-08-08', NULL, 3, 'Laureen', 'James', '13456857', 'F', 2);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (7, '2012-04-05', NULL, 5, 'Maureen', 'Young', '13406877', 'F', 1);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (8, '2014-07-05', NULL, 3, 'Bridget', 'Nice', '13456877', 'F', 2);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (9, '2014-07-07', NULL, 1, 'John', 'Weaver', '135676877', 'M', 2);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (10, '2014-08-10', NULL, 6, 'Lawrence', 'Jenkins', '4568889', 'M', 3);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (11, '2013-09-05', NULL, 6, 'Jennifer', 'Nieves', '13456877', 'F', 3);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (12, '2013-09-06', NULL, 6, 'John', 'Fitz', '134568457', 'M', 3);
INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (13, '2013-08-11', NULL, 5, 'Rohn', 'Regard', '134666877', 'M', 1);
	INSERT INTO EMPLOYEE (ID, HIRING_DATE, ADRESS, POSITION_ID, FIRST_NAME, LAST_NAME, PHONE, SEX, DEPT_ID) 
	VALUES (14, '2015-10-11', NULL, 1, 'Max', 'Lone', '134666877', 'M', 3);
	
INSERT INTO DEPARTMENT (ID, NAME, MANAGER_ID) 
	VALUES (1, 'Human Resources', 1);
INSERT INTO DEPARTMENT (ID, NAME, MANAGER_ID) 
	VALUES (2, 'IT', 9);
INSERT INTO DEPARTMENT (ID, NAME, MANAGER_ID) 
	VALUES (3, 'Support', 2);
